site_name: Panduan APG versi HTML
# site_url: https://mydomain.org/mysite
theme:
  name: material
  palette:

    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  
  # Mengatur font
  font:
    text: Open Sans
    code: JetBrains Mono

  # icon:
    # logo: material/book
  favicon: images/team.png
  logo: images/team.png

  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

  features:
    # - navigation.footer
    # - navigation.tabs
  

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # Fitur
  - attr_list


# Footer
copyright: Made with ❤️ by Masipnu | &copy; 2025

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/masipnu
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/masipnu
    - icon: fontawesome/brands/linkedin
      link: https://id.linkedin.com/in/ipnu-masyaid-8a6629177

extra_css:
  - stylesheets/extra.css